apiVersion: notifying.containers.ai/v1alpha1
kind: AlamedaNotificationTopic
metadata:
  name: sample
spec:
  channel:
    emails:
      - name: sample
        to:
          - "" # to@example.com
        cc:
          - "" # cc@example.com
  topics:
    - type:
        - "" # PodRegister
      subject:
        - namespace: "" # default
          name: "" # example
          kind: "" # Pod
      level:
        - info
      source:
        - component: "" # alameda-operator