apiVersion: federatorai.containers.ai/v1alpha1
kind: AlamedaService
metadata:
  name: example
  namespace: kroos-tutorial
spec:
  alameda-ai:
    image: "quay.io/prophetstor/alameda-ai"
    imagepullpolicy: "Always"
    storages:
    - size: 3Gi
      type: "pvc"
      usage: "log"
    version: "latest"
  enableexecution: true
  enablegui: true
  alameda-grafana:
    image: "grafana/grafana"
    version: "5.4.3"
    storages:
    - size: 2Gi
      type: "pvc"
      usage: "data"
  alameda-influxdb:
    image: "influxdb"
    imagepullpolicy: ""
    storages:
    - size: 2Gi
      type: "pvc"
      usage: "data"
    version: "1.7-alpine"
  prometheusservice: "https://prometheus-k8s.openshift-monitoring:9091"
  version: "v0.3.7"
  storages:
  - size: 1Gi
    type: "pvc"
    usage: "data"
  - type: "ephemeral"
    usage: "log"
