apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alameda-datahub
  namespace: {{.NameSpace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alameda-datahub
subjects:
- kind: ServiceAccount
  name: alameda-datahub 
  namespace: {{.NameSpace}}

 