apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-controller
  namespace: federatorai
  label:
    app: alameda
    component: admission-controller
  annotations:
    description: Defines how to deploy the admission-controller
    template.alpha.openshift.io/wait-for-ready: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-controller
  template:
    metadata:
      name: admission-controller
      labels:
        app: admission-controller
    spec:
      containers:
      - name: admission-controller
        image: quay.io/prophetstor/alameda-admission-rhel:v0.3.6
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 60m
            memory: 90Mi
          requests:
            cpu: 45m
            memory: 75Mi
        env:
        - name: ALAMEDA_ADMCTL_DEPLOYED_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ALAMEDA_ADMCTL_DATAHUB_ADDRESS
          value: "alameda-datahub.federatorai.svc:50050"
        - name: ALAMEDA_ADMCTL_ENABLE
          value: 'false'
        - name: ALAMEDA_ADMCTL_TLS_CERT_FILE
          value: /etc/tls-certs/tls.crt
        - name: ALAMEDA_ADMCTL_TLS_PRIVATE_KEY_FILE
          value: /etc/tls-certs/tls.key
        - name: ALAMEDA_ADMCTL_CA_CERT_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        volumeMounts:
        - mountPath: /etc/tls-certs
          name: tls-certs
          readOnly: false
      volumes:
      - name: tls-certs
        secret:
          secretName: admission-controller-tls
      serviceAccount: admission-controller
      serviceAccountName: admission-controller