apiVersion: apps/v1
kind: Deployment
metadata:
  name: alameda-grafana
  namespace: federatorai
  annotations:
    description: Defines how to deploy the application grafana
    template.alpha.openshift.io/wait-for-ready: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
        app: alameda-grafana
  template:
    metadata:
      labels:
        app: alameda-grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:5.4.3
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
            name: http
            protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
            subPath: grafana
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: 'my-alameda.grafana.pvc'
        - configMap:
            defaultMode: 420
            name: grafana-datasources
          name: grafana-datasources 