apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedemeter-api
  namespace: federatorai
spec:
  selector:
    matchLabels:
      app : fedemeter-api
  template:
      metadata:
        labels:
          app: fedemeter-api
      spec:
        containers:
        - name: fedemeter-api
          image: quay.io/prophetstor/fedemeter-api-ubi:v0.3.39
          imagePullPolicy: Always
          ports:
          - name: gui-fedemeter
            containerPort: 8999
          tty:  true
          envFrom:
            - configMapRef:
                name: fedemeter-config
        volumes:
        - name: fedemeter-data-storage
        - name: fedemeter-log-storage