apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{.NameSpace}}
  name: fedemeter-api
  annotations:
    ingress.kubernetes.io/cors-enable: "true"
    ingress.kubernetes.io/cors-allow-origin: "*"
    ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  #tls:
  #- secretName: fedemeter-api
  rules:
  - host:
    http:
      paths:
      - path: /fedemeter-api/v1/
        backend:
          serviceName: fedemeter-api
          servicePort: 8999