apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    component: alameda-grafana
  name: alameda-grafana
  namespace: {{.NameSpace}}
spec:
  port:
    targetPort: grafana-http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: alameda-grafana