apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    component: alameda-grafana
  name: alameda-grafana
  namespace: {{.NameSpace}}
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: alameda-grafana