apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    component: federatorai-rest
  name: federatorai-rest
  namespace: {{.NameSpace}}
spec:
  port:
    targetPort: restapi-http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: federatorai-rest
