apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    component: federatorai-rest
  name: federatorai-rest
  namespace: {{.NameSpace}}
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: federatorai-rest
