apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alamedadetections.analysis.containers.ai
spec:
  group: analysis.containers.ai
  names:
    kind: AlamedaDetection
    listKind: AlamedaDetectionList
    plural: alamedadetections
    singular: alamedadetection
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
