apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: federatorai-alameda-rabbitmq
  labels:
    app: rabbitmq
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]