apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.NameSpace}}-alameda-analyzer
rules:
# following is taken from Federatorai-operator CSV v0.0.1 clusterPermissions section
- verbs:
    - get
    - create
    - list
    - watch
  apiGroups:
    - ''
  resources:
    - configmaps
    - pods
- verbs:
    - '*'
  apiGroups:
    - analysis.containers.ai
  resources:
    - '*'
    - alamedadetections
- verbs:
    - get
    - list
    - watch
  apiGroups:
    - apps
    - extensions
  resources:
    - replicasets
    - deployments


