apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: federatorai-alameda-rabbitmq
  labels:
    app: rabbitmq
    chart: rabbitmq-0.3.0
    release: "alameda"
    heritage: "Tiller"
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]