apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: federatorai-alameda-evictioner
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - delete
- apiGroups:
  - autoscaling.containers.ai
  resources:
  - alamedascalers
  - alamedarecommendations
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
  - watch
  - update