apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kroos-tutorial.grafana.pvc
  namespace: kroos-tutorial
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi