kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: alameda-weave-scope-scc-anyuid
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
- MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:federatorai:alameda-weave-scope
- system:serviceaccount:federatorai:default
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
