kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: alameda-weave-scope-scc-admin
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedUnsafeSysctls:
- '*'
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:federatorai:alameda-weave-scope
- system:serviceaccount:federatorai:default
volumes:
- '*'
