apiVersion: v1
kind: Service
metadata:
  labels:
    app: admission-controller
  name: admission-controller
  namespace: federatorai
spec:
  ports:
  - port: 443
    targetPort: 8000
  selector:
    app: admission-controller