apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: admission-controller-tls
  labels:
    app: admission-controller
  name: admission-controller
  namespace: federatorai
spec:
  ports:
  - port: 443
    targetPort: 8000
  selector:
    app: admission-controller