apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: alameda-datahub-tls
  labels:
    app: alameda-influxdb
  name: alameda-influxdb
  namespace: federatorai
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    app: alameda-influxdb