apiVersion: v1
kind: Service
metadata:
  namespace: {{.NameSpace}}
  name: alameda-rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: http
      port: 15672
      targetPort: http
  selector:
    app: rabbitmq