apiVersion: v1
kind: Service
metadata:
  labels:
    component: alameda-influxdb
  name: alameda-influxdb
  namespace: {{.NameSpace}}
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    component: alameda-influxdb