apiVersion: v1
kind: Service
metadata:
  labels:
    component: alameda-grafana
  name: alameda-grafana
  namespace: {{.NameSpace}}
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31010
  selector:
    component: alameda-grafana