apiVersion: v1
kind: Service
metadata:
  labels:
    component: alameda-grafana
  name: alameda-grafana
  namespace: federatorai
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    component: alameda-grafana