apiVersion: v1
kind: Service
metadata:
  namespace: federatorai
  name: alameda-rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: stats
      port: 15672
      targetPort: stats
  selector:
    app: rabbitmq