apiVersion: v1
kind: Service
metadata:
  labels:
    component: alameda-grafana
  name: alameda-grafana
  namespace: {{.NameSpace}}
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: grafana-http
  - port: 3001
    targetPort: 3001
    name: grafana-https
  selector:
    component: alameda-grafana
