apiVersion: v1
kind: Service
metadata:
  labels:
    component: alameda-datahub
  name: alameda-datahub
  namespace: {{.NameSpace}}
spec:
  ports:
  - name: grpc
    port: 50050
  selector:
    component: alameda-datahub