apiVersion: v1
kind: Service
metadata:
  labels:
    app: alameda-grafana
  name: alameda-grafana
  namespace: kroos-tutorial
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: alameda-grafana 