apiVersion: v1
kind: Service
metadata:
  labels:
    app: alameda-datahub
  name: alameda-datahub
  namespace: kroos-tutorial
spec:
  ports:
  - name: grpc
    port: 50050
  selector:
    app: alameda-datahub