apiVersion: v1
kind: Service
metadata:
  name: cert-managet-webhook
  namespace: "{{.NameSpace}}" 
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: 6443
  selector:
    app: alameda
    component: alameda-cert-managet-webhook
