apiVersion: v1
kind: Service
metadata:
  labels:
    app: alameda-influxdb
  name: alameda-influxdb
  namespace: federatorai
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    app: alameda-influxdb