apiVersion: v1
kind: Service
metadata:
  name: fedemeter-api
  namespace: {{.NameSpace}}
  labels:
    app: fedemeter-api
spec:
  ports:
  - port: 8888
    targetPort: 8888
    name: fedemeter-api
  selector:
    app: fedemeter-api