apiVersion: v1
kind: Service
metadata:
  name: fedemeter-api
  namespace: federatorai
  labels:
    app: fedemeter-api
spec:
  ports:
  - port: 8999
    targetPort: 8999
    nodePort: 31000
    name: fedemeter-api
  selector:
    app: fedemeter-api
  type: NodePort