apiVersion: v1
kind: Service
metadata:
  name: fedemeter-influxdb
  namespace: {{.NameSpace}}
  labels:
    app: fedemeter-influxdb
spec:
  ports:
  - port: 8086
    name: http-fedemeter-influxdb
  selector:
    app: fedemeter-influxdb