apiVersion: v1
kind: Service
metadata:
  labels:
    component: federatorai-rest
  name: federatorai-rest
  namespace: {{.NameSpace}}
spec:
  ports:
  - name: restapi
    port: 5055
  selector:
    component: federatorai-rest
