apiVersion: v1
kind: Service
metadata:
  labels:
    component: federatorai-rest
  name: federatorai-rest
  namespace: {{.NameSpace}}
spec:
  ports:
  - name: restapi-http
    port: 5055
    targetPort: 5055
  - name: restapi-https
    port: 5056
    targetPort: 5056
  selector:
    component: federatorai-rest
