apiVersion: apps/v1
kind: Deployment
metadata:
  name: federatorai-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: federatorai-operator
  template:
    metadata:
      labels:
        name: federatorai-operator
    spec:
      serviceAccountName: federatorai-operator
      containers:
        - name: federatorai-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - federatorai-operator
          imagePullPolicy: Always
          ports:
          - name: metrics
            containerPort: 8383
            protocol: TCP
          env:
            - name: FEDERATORAI_OPERATOR_METRICS_PORT
              value: "8383"
            - name: FEDERATORAI_OPERATOR_WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "federatorai-operator"
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3            