apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.NameSpace}}-alameda-grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.NameSpace}}-alameda-grafana
subjects:
- kind: ServiceAccount
  name: alameda-grafana
  namespace: {{.NameSpace}}