apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.NameSpace}}-alameda-notifier-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.NameSpace}}-alameda-notifier-role
subjects:
- kind: ServiceAccount
  name: alameda-notifier 
  namespace: {{.NameSpace}}
