apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: federatorai-alameda-datahub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: federatorai-alameda-datahub
subjects:
- kind: ServiceAccount
  name: alameda-datahub
  namespace: federatorai