apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: federatorai-alameda-evictioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: federatorai-alameda-evictioner
subjects:
- kind: ServiceAccount
  name: alameda-evictioner
  namespace: federatorai