apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.NameSpace}}-certmanager-cert-manager-leaderelection 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.NameSpace}}-certmanager-cert-manager-leaderelection
subjects:
  - name: certmanager-cert-manager
    namespace: "{{.NameSpace}}"
    kind: ServiceAccount