apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: federatorai-operator
subjects:
- kind: ServiceAccount
  name: federatorai-operator
  namespace: federatorai
roleRef:
  kind: ClusterRole
  name: federatorai-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: federatorai-operator:auth-delegator
subjects:
- kind: ServiceAccount
  name: federatorai-operator
  namespace: federatorai
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator