apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admission-controller-data.pvc
  namespace: federatorai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 