apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: federatorai-agent-preloader-log.pvc
  namespace: {{.NameSpace}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi