apiVersion: v1
kind: ConfigMap
metadata:
  name: alameda-executor-config
  namespace: {{.NameSpace}}
data:
  config.yml: |-
    datahub:
      address: "alameda-datahub.{{.NameSpace}}.svc"
      port: 50050
    executor:
      check-cycle: 3   # second
      expire-time: 300 # second
      enable: true