apiVersion: v1
kind: ConfigMap
metadata:
  name: alameda-recommender-config
  namespace: federatorai
data:
  config.toml: |-
    [global]
    hpa_interval = 180
    vpa_short_interval = 300
    vpa_long_interval = 3600
    debug = false

    [datahub]
    address = "alameda-datahub.federatorai.svc"
    port = 50050

    [hpa_scaling]
    alpha = 0.25
    limits_threshold = 0.9
    sample_rate = 15
    period_rate = 60
    period_count = 5
    