apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: certmanager-webhook-webhook-tls
  namespace: "{{.NameSpace}}" 
spec:
  secretName: certmanager-webhook-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: certmanager-webhook-ca
  dnsNames:
  - certmanager-webhook
  - certmanager-webhook.{{.NameSpace}}
  - certmanager-webhook.{{.NameSpace}}.svc
